export const fakeData = [
  {
    job_id: "PoyX7RT8Se1Rt-ajAAAAAA==",
    job_title: "Front-End Software Developer - Clearing",
    employer_name: "Marex",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsLEwc_ZkBvrRiypZPsPnTZqG8zy75LqPP-Ks3&s=0",
    employer_website: "http://www.marex.com/",
    job_publisher: "LinkedIn",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.linkedin.com/jobs/view/front-end-software-developer-clearing-at-marex-4260482599?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/front-end-software-developer-clearing-at-marex-4260482599?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Built In",
        apply_link:
          "https://builtin.com/job/front-end-software-developer-clearing/6552371?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "Diversified. Resilient. Dynamic.\n\nMarex is a global financial services platform, providing essential liquidity, market access and infrastructure services to clients in the energy, commodities and financial markets.\n\nThe Group provides comprehensive breadth and depth of coverage across four core services: Market Making, Clearing, Hedging and Investment Solutions and Agency and Execution. It has a major franchise in many major metals, energy and agricultural products, executing around 50 million trades and clearing 205 million contracts in 2022. The Group provides access to the world’s major commodity markets, covering a broad range of clients that include some of the largest commodity producers, consumers and traders, banks, hedge funds and asset managers.\n\nWith more than 35 offices around the globe, and over 2300 dedicated people enabling access to exchanges and technology-powered services.\n\nFor more information visit www.marex.com\n\nPurpose Of Role\n\nThe Software Developer, Clearing (Front-End) contributes to the creation and enhancement of secure, responsive, web applications tailored for front-to-back clearing technology. Expertise in developing, React, and Typescript, coupled with a strong emphasis on testing, are instrumental in delivering robust and reliable applications.\n\nEmphasis on front end technology development.\n\nThis role leverages architectural experience to mature Marex’s existing software and efficiently migrate legacy platforms to the cloud and works closely with the platform engineering team to ensure seamless integration and deployment, playing a crucial part in advancing Marex’s technology stack and maintaining the highest standards of performance security.\n\nMarex has unique access across markets with significant share globally both on and off exchange. The depth of knowledge amongst its teams and divisions provides its customers with clear advantage, and its technology-led service provides access to all major exchanges, order-flow management via screen, voice and DMA, plus award-winning data, insights and analytics.\n\nThe Technology Department delivers differentiation, scalability and security for the business. Reporting to the COO, Technology provides digital tools, software services and infrastructure globally to all business groups. Software development and support teams work in agile ‘streams’ aligned to specific business areas. Our other teams work enterprise-wide to provide critical services including our global service desk, network and system infrastructure, IT operations, security, enterprise architecture and design.\n\nThe Software Development function creates and maintains applications, frameworks and other software components to deliver to business requirements. Developers conceive, specify, design, code, document, test, and delivery bug fixes as needed to provide high quality software solutions. Each Development team is aligned to one of Marex’s business divisions and works with a corresponding Business Technology and Application Support team\n\nResponsibilities\n• Design, code and test all components of modern web applications.\n• Contribute to the overall architecture and design of the technology created/maintained by the development delivery team.\n• Develop solutions to a high standard that is maintainable, testable and meets the requirement’s acceptance criteria.\n• Adhere to development best practices and processes.\n• Communicate with team members, introduce ideas and keep abreast of the latest technologies.\n• Liaise with business users to gather application requirements\n• Ensure delivered systems are of production quality. Ensure software is adequately documented for handover to the business.\n• Follow coding standards and defined development process.\n• Resolve third line support issues in a professional and timely manner\n• Ensuring compliance with the company’s regulatory requirements under the SEC, FINRA, NFA, CFTC and other applicable exchanges.\n• Adhere to the operational risk framework for your role ensuring that all regulatory or company determined parameters are complied with.\n• Role model for demonstrating highest level standards of integrity and conduct and reflecting Company Values.\n• At all times complying with Marex’s Code of Conduct\n• To ensure that you are fully aware of and adhere to internal policies that relate to you, your role or any other activities for which you have any level of responsibility\n• To report any breaches of policy to Compliance and/ or your supervisor as required\n• To escalate risk events immediately\n• To provide input to risk management processes, as required.\n\nThe Company may require you to carry out other duties from time to time.\n\nCompetencies, Skills And Experience\n\nCompetencies\n• A collaborative team player, approachable, self-efficient and influences a positive work environment\n• Demonstrates curiosity\n• Resilient in a challenging, fast-paced environment\n• Excels at building relationships, networking and influencing others\n• Strategic collaborator with insight and agility, able to anticipate future challenges, ensuring operational effectiveness\n\nEssential\n\nSkills and Experience\n• 5+ years of front-end development (React).\n• Experience and knowledge of Agile and scrum development methodologies.\n• Knowledge of TDD (Test Driven Development) and BDD (Behavior Driven Development)\n• Excellent verbal and written communication skills.\n• Experience working in a regulated environment and knowledge of the risk and compliance requirements associated with this.\n• Bachelor's Degree is preferred.\n\nPreferred\n• Experience with NoSQL or RDMS databases.\n• Experience working with Modern CI/CD and DevOps practices.\n• Experience with Cloud technology, ideally AWS (Amazon Web Services.\n• Financial services experience preferred but not required.\n\nSalary Range: $120,000 to $175,000 per year and eligible for discretionary bonus.\n\nCompany Values\n\nMarex Benefits for 2025\n\nActing as a role model for the values of the Company:\n\nRespect\n\nClients are at the heart of our business, with superior execution and superb client service the foundation of the firm. We respect our clients and always treat them fairly.\n\nIntegrity\n\nDoing business the right way is the only way. We hold ourselves to a high ethical standard in everything we do – our clients expect this and we demand it of ourselves.\n\nCollaborative\n\nWe work in teams – open and direct communication and the willingness to work hard and collaboratively are the basis for effective teamwork. Working well with others is necessary for us to succeed at what we do.\n\nDeveloping our People\n\nOur people are the basis of our competitive advantage. We look to “grow our own” and make Marex the place ambitious, hardworking, talented people choose to build their careers.\n\nAdaptable and Nimble\n\nOur size and flexibility is an advantage. We are big enough to support our client’s various needs, and adaptable and nimble enough to respond quickly to changing conditions or requirements. A non-bureaucratic, but well controlled environment fosters initiative as well as employee satisfaction.\n\nMarex is fully committed to the elimination of unlawful or unfair discrimination and values the differences that a diverse workforce brings to the company.\n\nWe are an equal opportunity employer. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, disability status, protected veteran status, or any other characteristic protected by the law.",
    job_is_remote: false,
    job_posted_at: "12 hours ago",
    job_posted_at_timestamp: 1751414400,
    job_posted_at_datetime_utc: "2025-07-02T00:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DPoyX7RT8Se1Rt-ajAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_min_salary: 120000,
    job_max_salary: 175000,
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "A collaborative team player, approachable, self-efficient and influences a positive work environment",
        "Demonstrates curiosity",
        "Resilient in a challenging, fast-paced environment",
        "Excels at building relationships, networking and influencing others",
        "Strategic collaborator with insight and agility, able to anticipate future challenges, ensuring operational effectiveness",
        "5+ years of front-end development (React)",
        "Experience and knowledge of Agile and scrum development methodologies",
        "Knowledge of TDD (Test Driven Development) and BDD (Behavior Driven Development)",
        "Excellent verbal and written communication skills",
        "Experience working in a regulated environment and knowledge of the risk and compliance requirements associated with this",
        "Doing business the right way is the only way",
        "We are big enough to support our client’s various needs, and adaptable and nimble enough to respond quickly to changing conditions or requirements",
        "A non-bureaucratic, but well controlled environment fosters initiative as well as employee satisfaction",
      ],
      Benefits: [
        "Salary Range: $120,000 to $175,000 per year and eligible for discretionary bonus",
        "Marex Benefits for 2025",
        "Our size and flexibility is an advantage",
      ],
      Responsibilities: [
        "The Software Developer, Clearing (Front-End) contributes to the creation and enhancement of secure, responsive, web applications tailored for front-to-back clearing technology",
        "Software development and support teams work in agile ‘streams’ aligned to specific business areas",
        "Our other teams work enterprise-wide to provide critical services including our global service desk, network and system infrastructure, IT operations, security, enterprise architecture and design",
        "The Software Development function creates and maintains applications, frameworks and other software components to deliver to business requirements",
        "Developers conceive, specify, design, code, document, test, and delivery bug fixes as needed to provide high quality software solutions",
        "Each Development team is aligned to one of Marex’s business divisions and works with a corresponding Business Technology and Application Support team",
        "Design, code and test all components of modern web applications",
        "Contribute to the overall architecture and design of the technology created/maintained by the development delivery team",
        "Develop solutions to a high standard that is maintainable, testable and meets the requirement’s acceptance criteria",
        "Adhere to development best practices and processes",
        "Communicate with team members, introduce ideas and keep abreast of the latest technologies",
        "Liaise with business users to gather application requirements",
        "Ensure delivered systems are of production quality",
        "Ensure software is adequately documented for handover to the business",
        "Follow coding standards and defined development process",
        "Resolve third line support issues in a professional and timely manner",
        "Ensuring compliance with the company’s regulatory requirements under the SEC, FINRA, NFA, CFTC and other applicable exchanges",
        "Adhere to the operational risk framework for your role ensuring that all regulatory or company determined parameters are complied with",
        "Role model for demonstrating highest level standards of integrity and conduct and reflecting Company Values",
        "At all times complying with Marex’s Code of Conduct",
        "To ensure that you are fully aware of and adhere to internal policies that relate to you, your role or any other activities for which you have any level of responsibility",
        "To report any breaches of policy to Compliance and/ or your supervisor as required",
        "To escalate risk events immediately",
        "To provide input to risk management processes, as required",
        "The Company may require you to carry out other duties from time to time",
      ],
    },
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },

  {
    job_id: "VAXenrrvrJiriSCJAAAAAA==",
    job_title: "Senior Developer - Chatbot Technical Lead",
    employer_name: "United Airlines",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6e93QF6Pdyb8sYG-83_wUFBI3uqDijJVqqAKm&s=0",
    employer_website: "https://www.united.com",
    job_publisher: "United Airlines Jobs",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://careers.united.com/us/en/job/CHI00000490/Senior-Developer-Chatbot-Technical-Lead?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "United Airlines Jobs",
        apply_link:
          "https://careers.united.com/us/en/job/CHI00000490/Senior-Developer-Chatbot-Technical-Lead?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/senior-developer-chatbot-technical-lead-at-united-airlines-4233880930?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "SimplyHired",
        apply_link:
          "https://www.simplyhired.com/job/gDTWS8t5dK9oJNO7uodh0BeOUuXnqqOZ3MVkFtWJcq4LxzDv7ewysQ?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "Achieving our goals starts with supporting yours. Grow your career, access top-tier health and wellness benefits, build lasting connections with your team and our customers, and travel the world using our extensive route network.\n\nCome join us to create what’s next. Let’s define tomorrow, together.\n\nDescription\n\nUnited's Digital Technology team is comprised of many talented individuals all working together with cutting-edge technology to build the best airline in the history of aviation. Our team designs, develops and maintains massively scaling technology solutions brought to life with innovative architectures, data analytics, and digital solutions.\n\nJob overview and responsibilities:\n\nThe Senior Developer, IT will be responsible for the development of our critical applications within the contact centers. This role will need to have the expertise on technical development in Conversational Contact Center technologies including Web Chat, Voice IVR, Web Applications & Cloud platforms.\n• Lead development, execution, and delivery of artifacts/code involving Conversational AI, IVR systems, chatbot/web chat solutions, and cloud-native web applications\n• Collaborate with technology leads/developers, business SMEs, UX designers, and technology stakeholders to define technical deliveries\n• Drive integration of Voice and Web-based channels with back-end systems, APIs and analytics platforms\n• Champion Agile/Scrum methodologies, conducting sprint planning, stand-ups, and retrospectives\n• Lead API integrations between internal platforms, external systems, and cloud services\n• Collaborate with development, infrastructure, and product teams to gather integration requirements and translate them into scalable technical solutions\n• Lead unit and integration testing and assist QA teams with end-to-end testing\n• Stay current with industry best practices and emerging technologies in API development and integration\n• Highlight and document risks, issues, blockers and dependencies; discuss with team project manager on regular basis\n• Coordinate with Cloud infrastructure teams (AWS, Azure, or GCP) to ensure scalable, secure, and high-performance deployments\n• Track delivery milestones and interdependencies across multiple teams\n• Oversee vendor relationships and third-party integrations when applicable\n• Support and guide the team in removing blockers, maintaining momentum, and ensuring quality\n• 4+ years of hands on technical experience in Contact Center & CX platforms\n• Proven experience delivering IVR, web chat, and AI-powered virtual assistant solutions\n• Solid technical understanding of cloud platforms (AWS/Azure/GCP), APIs, CI/CD, web technologies, and DevOps practices\n• Strong organizational and stakeholder management skills across technical and non-technical teams\n• Experience with Agile/Scrum or SAFe frameworks and tools (e.g., Jira, Confluence, Azure DevOps)\n• Excellent communication, leadership, and documentation abilities\n• Knowledge of APIs, JSON, XML, and OAuth\n• Experience with language: Node.js, Python\n• Familiarity with CI/CD pipelines/DevOps and version control tools like Git\n• Knowledge of customer journey mapping, persona design, and voice UX best practices\n• Familiarity with compliance standards (e.g., GDPR, HIPAA, PCI-DSS) in cloud and CX solutions\n\nQualifications\n\nWhat’s needed to succeed (Minimum Qualifications):\n• Bachelor's degree or 4 years of relevant work experience in Computer science engineering or relevant field\n• Nice to have:\n• Cloud certification\n• SaFe Agile\n• 4+ years of experience in design, development, documenting, testing, and debugging of new and existing software systems and/or applications for market sale or large-scale proprietary software for internal use in an agile environment.\n• Web development, API integrations, Cloud technologies, contact center/IVR technologies, Chatbot creation & integrations\n• Experience in Conversational AI domains\n• Experience in chat/voice bots\n• Must be legally authorized to work in the United States for any employer without sponsorship\n• Successful completion of interview required to meet job qualification\n• Reliable, punctual attendance is an essential function of the position\n\nWhat will help you propel from the pack (Preferred Qualifications):\n• Knowledge of NLP/NLU, LLMs, or Generative AI frameworks (e.g., OpenAI, Google Vertex AI, Amazon Bedrock) including data preparation, prompt design, testing, and feedback loops\n\nThe base pay range for this role is $109,820.00 to $149,600.00.\nThe base salary range/hourly rate listed is dependent on job-related, factors such as experience, education, and skills. This position is also eligible for bonus and/or long-term incentive compensation awards.\n\nYou may be eligible for the following competitive benefits: medical, dental, vision, life, accident & disability, parental leave, employee assistance program, commuter, paid holidays, paid time off, 401(k) and flight privileges.\n\nUnited Airlines is an equal opportunity employer. United Airlines recruits, employs, trains, compensates and promotes regardless of race, religion, color, national origin, gender identity, sexual orientation, physical ability, age, veteran status and other protected status as required by applicable law. Equal Opportunity Employer - Minorities/Women/Veterans/Disabled/LGBT.\n\nWe will ensure that individuals with disabilities are provided reasonable accommodation to participate in the job application or interview process, to perform crucial job functions. Please contact JobAccommodations@united.com to request accommodation.",
    job_is_remote: false,
    job_posted_at: "12 hours ago",
    job_posted_at_timestamp: 1751414400,
    job_posted_at_datetime_utc: "2025-07-02T00:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: ["health_insurance", "paid_time_off", "dental_coverage"],
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DVAXenrrvrJiriSCJAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "4+ years of hands on technical experience in Contact Center & CX platforms",
        "Proven experience delivering IVR, web chat, and AI-powered virtual assistant solutions",
        "Solid technical understanding of cloud platforms (AWS/Azure/GCP), APIs, CI/CD, web technologies, and DevOps practices",
        "Strong organizational and stakeholder management skills across technical and non-technical teams",
        "Experience with Agile/Scrum or SAFe frameworks and tools (e.g., Jira, Confluence, Azure DevOps)",
        "Excellent communication, leadership, and documentation abilities",
        "Knowledge of APIs, JSON, XML, and OAuth",
        "Experience with language: Node.js, Python",
        "Familiarity with CI/CD pipelines/DevOps and version control tools like Git",
        "Knowledge of customer journey mapping, persona design, and voice UX best practices",
        "Familiarity with compliance standards (e.g., GDPR, HIPAA, PCI-DSS) in cloud and CX solutions",
        "Bachelor's degree or 4 years of relevant work experience in Computer science engineering or relevant field",
        "Nice to have:",
        "Cloud certification",
        "SaFe Agile",
        "4+ years of experience in design, development, documenting, testing, and debugging of new and existing software systems and/or applications for market sale or large-scale proprietary software for internal use in an agile environment",
        "Web development, API integrations, Cloud technologies, contact center/IVR technologies, Chatbot creation & integrations",
        "Experience in Conversational AI domains",
        "Experience in chat/voice bots",
        "Must be legally authorized to work in the United States for any employer without sponsorship",
        "Successful completion of interview required to meet job qualification",
        "Reliable, punctual attendance is an essential function of the position",
      ],
      Benefits: [
        "The base pay range for this role is $109,820.00 to $149,600.00",
        "The base salary range/hourly rate listed is dependent on job-related, factors such as experience, education, and skills",
        "This position is also eligible for bonus and/or long-term incentive compensation awards",
        "You may be eligible for the following competitive benefits: medical, dental, vision, life, accident & disability, parental leave, employee assistance program, commuter, paid holidays, paid time off, 401(k) and flight privileges",
      ],
      Responsibilities: [
        "The Senior Developer, IT will be responsible for the development of our critical applications within the contact centers",
        "This role will need to have the expertise on technical development in Conversational Contact Center technologies including Web Chat, Voice IVR, Web Applications & Cloud platforms",
        "Lead development, execution, and delivery of artifacts/code involving Conversational AI, IVR systems, chatbot/web chat solutions, and cloud-native web applications",
        "Collaborate with technology leads/developers, business SMEs, UX designers, and technology stakeholders to define technical deliveries",
        "Drive integration of Voice and Web-based channels with back-end systems, APIs and analytics platforms",
        "Champion Agile/Scrum methodologies, conducting sprint planning, stand-ups, and retrospectives",
        "Lead API integrations between internal platforms, external systems, and cloud services",
        "Collaborate with development, infrastructure, and product teams to gather integration requirements and translate them into scalable technical solutions",
        "Lead unit and integration testing and assist QA teams with end-to-end testing",
        "Stay current with industry best practices and emerging technologies in API development and integration",
        "Highlight and document risks, issues, blockers and dependencies; discuss with team project manager on regular basis",
        "Coordinate with Cloud infrastructure teams (AWS, Azure, or GCP) to ensure scalable, secure, and high-performance deployments",
        "Track delivery milestones and interdependencies across multiple teams",
        "Oversee vendor relationships and third-party integrations when applicable",
        "Support and guide the team in removing blockers, maintaining momentum, and ensuring quality",
      ],
    },
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },

  {
    job_id: "Rozruq5_-kglTWkqAAAAAA==",
    job_title: "Golang Developer",
    employer_name: "SoTalent",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOjKyzl30jL2eYFJLWyAQhVQb0Zg7ks7SQrT0T&s=0",
    employer_website: null,
    job_publisher: "LinkedIn",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.linkedin.com/jobs/view/golang-developer-at-sotalent-4256938844?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/golang-developer-at-sotalent-4256938844?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Iitjobs",
        apply_link:
          "https://www.iitjobs.com/job/golang-developer-chicago-il-usa-united-software-group-inc-12592?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Monster",
        apply_link:
          "https://www.monster.com/job-openings/golang-developer-chicago-il--b5cc6680-859c-4166-9160-a6e2f71e79d0?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Golang Job",
        apply_link:
          "https://golangjob.xyz/job/2KS2Nu4zIucFP0LenW72JXdAoO1?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "RIT Solutions Inc",
        apply_link:
          "https://ritsolinc.jobs.net/job/J3N3B36L64V4QLWXT6H?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "WhatJobs",
        apply_link:
          "https://www.whatjobs.com/gfj/2025986067?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Jobs Trabajo.org",
        apply_link:
          "https://us.trabajo.org/job-2611-9ac6cbe5a76b9b4598a1e9436ab28f5c?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Recruit.net",
        apply_link:
          "https://www.recruit.net/job/golang-developer-jobs/C93215455C14A164?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "Job Title: Golang Developer\n\nLocation: Chicago, IL\n\nType: Full time\n\nJoin a fast-growing engineering team building advanced, data-driven advertising platforms. As a Senior Golang Engineer, you’ll design and scale backend services, contribute to high-performance data pipelines, and help shape the future of audience-targeting technology. If you thrive in solving complex challenges and working in a dynamic, agile environment — this role is for you.\n\nWhat You’ll Do:\n• Build and maintain backend services, APIs, and applications using Golang\n• Develop scalable audience targeting and identity systems with low-latency performance\n• Architect big data ingestion and processing pipelines to manage data at scale\n• Collaborate with cross-functional teams to translate technical and product requirements into solutions\n• Deploy and manage infrastructure in AWS using Kubernetes and containerization tools\n• Troubleshoot performance and reliability issues in a cloud-native environment\n• Mentor junior engineers and guide best practices across architecture and DevOps\n• Build tools for managing data pipelines, scheduling, and performance tracking\n• Promote data quality, security, and scalability through automation and monitoring\n• Document technical decisions, implementation plans, and testing strategies\n\nWhat You Bring:\n• Bachelor's or Master’s degree in Computer Science or related field\n• 3+ years of experience coding in Golang, including working with gRPC and ProtoBuf\n• Strong background in microservices, Kubernetes, and AWS infrastructure\n• Proficient in SQL and big data technologies (e.g., Snowflake, Databricks, Spark, Presto)\n• Experience with CI/CD tools (e.g., Jenkins, Terraform) and observability platforms (e.g., Datadog, Grafana, Prometheus)\n• Excellent problem-solving and communication skills\n• Ability to lead initiatives and work in a fast-paced, evolving environment\n• Bonus: Experience in ad tech or audience targeting, AWS certification",
    job_is_remote: false,
    job_posted_at: "16 hours ago",
    job_posted_at_timestamp: 1751400000,
    job_posted_at_datetime_utc: "2025-07-01T20:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DRozruq5_-kglTWkqAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's or Master’s degree in Computer Science or related field",
        "3+ years of experience coding in Golang, including working with gRPC and ProtoBuf",
        "Strong background in microservices, Kubernetes, and AWS infrastructure",
        "Proficient in SQL and big data technologies (e.g., Snowflake, Databricks, Spark, Presto)",
        "Experience with CI/CD tools (e.g., Jenkins, Terraform) and observability platforms (e.g., Datadog, Grafana, Prometheus)",
        "Excellent problem-solving and communication skills",
        "Ability to lead initiatives and work in a fast-paced, evolving environment",
        "Bonus: Experience in ad tech or audience targeting, AWS certification",
      ],
      Responsibilities: [
        "As a Senior Golang Engineer, you’ll design and scale backend services, contribute to high-performance data pipelines, and help shape the future of audience-targeting technology",
        "If you thrive in solving complex challenges and working in a dynamic, agile environment — this role is for you",
        "Build and maintain backend services, APIs, and applications using Golang",
        "Develop scalable audience targeting and identity systems with low-latency performance",
        "Architect big data ingestion and processing pipelines to manage data at scale",
        "Collaborate with cross-functional teams to translate technical and product requirements into solutions",
        "Deploy and manage infrastructure in AWS using Kubernetes and containerization tools",
        "Troubleshoot performance and reliability issues in a cloud-native environment",
        "Mentor junior engineers and guide best practices across architecture and DevOps",
        "Build tools for managing data pipelines, scheduling, and performance tracking",
        "Promote data quality, security, and scalability through automation and monitoring",
        "Document technical decisions, implementation plans, and testing strategies",
      ],
    },
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },

  {
    job_id: "sUs1o__TTVtBFLpoAAAAAA==",
    job_title: "Customer Developer, AI Infrastructure",
    employer_name: "Google",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDmYiMmyAegwA56C0JBQj8E2CLY48y4q9GSXnR&s=0",
    employer_website: "https://www.google.com/",
    job_publisher: "LinkedIn",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.linkedin.com/jobs/view/customer-developer-ai-infrastructure-at-google-4259195547?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/customer-developer-ai-infrastructure-at-google-4259195547?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Indeed",
        apply_link:
          "https://www.indeed.com/viewjob?jk=78f05ea72fbdf996&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Glassdoor",
        apply_link:
          "https://www.glassdoor.com/job-listing/customer-developer-ai-infrastructure-google-JV_IC1128808_KO0,36_KE37,43.htm?jl=1009798360136&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "SimplyHired",
        apply_link:
          "https://www.simplyhired.com/job/Dm-cppkVrlg_7dRBZEe7SUbvlualSZuC8Uvs3pA-HjEU0iK96PlyAA?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "Note: By applying to this position you will have an opportunity to share your preferred working location from the following: Toronto, ON, Canada; Sunnyvale, CA, USA; Austin, TX, USA; Chicago, IL, USA; Seattle, WA, USA; San Francisco, CA, USA.Minimum qualifications:\n• Bachelor's degree in Computer Science, Mathematics, a related technical field, or equivalent practical experience.\n• 10 years of experience with cloud infrastructure.\n• Experience building and operationalizing machine learning models.\n• Experience in delivering technical presentations while leading discovery and planning sessions that are aligned jointly with the customer with defined scope and success criteria.\n\nPreferred qualifications:\n• Experience designing/architecting large-scale infrastructure farms for specialist AI use cases.\n• Experience training and fine tuning large models (i.e., image, language, segmentation, recommendation, genomics) with accelerators.\n• Experience with running MLPerf benchmarks.\n• Experience with containerization and Kubernetes (K8s) on cloud.\n• Experience with performance profiling tools.\n• Ability to engage with C-level or executive business leaders and influence decisions.\n\nAbout The Job\n\nWhen leading companies choose Google Cloud, it's a huge win for spreading the power of cloud computing globally. Once educational institutions, government agencies, and other businesses sign on to use Google Cloud products, you come in to facilitate making their work more productive, mobile, and collaborative. You listen and deliver what is most helpful for the customer. You assist fellow sales Googlers by problem-solving key technical issues for our customers. You liaise with the product marketing management and engineering teams to stay on top of industry trends and devise enhancements to Google Cloud products.\n\nAs a Customer Developer, you will partner with technical Sales teams as a subject matter expert in Artificial Intelligence and Machine Learning (AI/ML) to differentiate Google Cloud to our customers. You will help prospective and existing customers and partners understand the power of Google Cloud, develop creative cloud solutions and architectures to solve their business test, engage in proofs of concepts, and troubleshoot any technical questions and roadblocks. You will use your expertise and presentation skills to engage with customers to understand their business and technical requirements, and persuasively present practical and useful solutions on Google Cloud. You will partner with internal engineering stakeholders to improve products and build solutions, optimizing for results when in production and identifying innovative ways to multiply your impact and the impact of the team as a whole.\n\nGoogle Cloud accelerates every organization’s ability to digitally transform its business and industry. We deliver enterprise-grade solutions that leverage Google’s cutting-edge technology, and tools that help developers build more sustainably. Customers in more than 200 countries and territories turn to Google Cloud as their trusted partner to enable growth and solve their most critical business problems.\n\nThe US base salary range for this full-time position is $147,000-$218,000 + bonus + equity + benefits. Our salary ranges are determined by role, level, and location. Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training. Your recruiter can share more about the specific salary range for your preferred location during the hiring process.\n\nPlease note that the compensation details listed in US role postings reflect the base salary only, and do not include bonus, equity, or benefits. Learn more about benefits at Google .\n\nResponsibilities\n• Be a trusted advisor to our top customers, helping them understand and incorporate AI accelerators into their overall cloud strategy by recommending migration paths, integration strategies, and application architecture that incorporate Google Cloud AI optimized infrastructure.\n• Demonstrate how Google Cloud is differentiated, highlighting the power of accelerators by working with customers on POCs, demonstrating features, optimizing model performance, profiling, and benchmarking.\n• Build repeatable assets to enable other customers and internal teams.\n• Influence Google Cloud strategy at the intersection of infrastructure and AI/ML by advocating for enterprise customer requirements.\n• Travel to customer sites and events as needed.\n\nGoogle is proud to be an equal opportunity workplace and is an affirmative action employer. We are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity or Veteran status. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements. See also Google's EEO Policy and EEO is the Law. If you have a disability or special need that requires accommodation, please let us know by completing our Accommodations for Applicants form .",
    job_is_remote: false,
    job_posted_at: "49 minutes ago",
    job_posted_at_timestamp: 1751454000,
    job_posted_at_datetime_utc: "2025-07-02T11:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: ["health_insurance"],
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DsUs1o__TTVtBFLpoAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_min_salary: 147000,
    job_max_salary: 218000,
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science, Mathematics, a related technical field, or equivalent practical experience",
        "10 years of experience with cloud infrastructure",
        "Experience building and operationalizing machine learning models",
        "Experience in delivering technical presentations while leading discovery and planning sessions that are aligned jointly with the customer with defined scope and success criteria",
      ],
      Benefits: [
        "The US base salary range for this full-time position is $147,000-$218,000 + bonus + equity + benefits",
        "Our salary ranges are determined by role, level, and location",
        "Within the range, individual pay is determined by work location and additional factors, including job-related skills, experience, and relevant education or training",
        "Your recruiter can share more about the specific salary range for your preferred location during the hiring process",
      ],
      Responsibilities: [
        "You listen and deliver what is most helpful for the customer",
        "You assist fellow sales Googlers by problem-solving key technical issues for our customers",
        "You liaise with the product marketing management and engineering teams to stay on top of industry trends and devise enhancements to Google Cloud products",
        "As a Customer Developer, you will partner with technical Sales teams as a subject matter expert in Artificial Intelligence and Machine Learning (AI/ML) to differentiate Google Cloud to our customers",
        "You will help prospective and existing customers and partners understand the power of Google Cloud, develop creative cloud solutions and architectures to solve their business test, engage in proofs of concepts, and troubleshoot any technical questions and roadblocks",
        "You will use your expertise and presentation skills to engage with customers to understand their business and technical requirements, and persuasively present practical and useful solutions on Google Cloud",
        "You will partner with internal engineering stakeholders to improve products and build solutions, optimizing for results when in production and identifying innovative ways to multiply your impact and the impact of the team as a whole",
        "Be a trusted advisor to our top customers, helping them understand and incorporate AI accelerators into their overall cloud strategy by recommending migration paths, integration strategies, and application architecture that incorporate Google Cloud AI optimized infrastructure",
        "Demonstrate how Google Cloud is differentiated, highlighting the power of accelerators by working with customers on POCs, demonstrating features, optimizing model performance, profiling, and benchmarking",
        "Build repeatable assets to enable other customers and internal teams",
        "Influence Google Cloud strategy at the intersection of infrastructure and AI/ML by advocating for enterprise customer requirements",
        "Travel to customer sites and events as needed",
      ],
    },
    job_onet_soc: "15111100",
    job_onet_job_zone: "5",
  },

  {
    job_id: "zpsZQLZ5duQi3MKKAAAAAA==",
    job_title: "W2 Only - .NET Core Developer (F2F Interview, W2 role- NO H1B)",
    employer_name: "IT ENGAGEMENTS INC",
    employer_logo: null,
    employer_website: null,
    job_publisher: "ZipRecruiter",
    job_employment_type: "Contractor",
    job_employment_types: ["CONTRACTOR", "CONTRACTOR"],
    job_apply_link:
      "https://www.ziprecruiter.com/c/IT-ENGAGEMENTS-INC/Job/W2-Only-.NET-Core-Developer-(F2F-Interview,-W2-role-NO-H1B)/-in-Chicago,IL?jid=04babaff6ee2c7db&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: true,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/IT-ENGAGEMENTS-INC/Job/W2-Only-.NET-Core-Developer-(F2F-Interview,-W2-role-NO-H1B)/-in-Chicago,IL?jid=04babaff6ee2c7db&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: true,
      },
    ],
    job_description:
      "Greetings from IT Engagements\n\nRole: .NET Core Developer (W2 Role only, NO H1B)\n\nLocation: Chicago, IL (Must need local DL)\n\nIf you are not in Chicago or your candidates are NOT in Chicago we will not contact you or reach out to you – this is a hybrid role 3 days ON-SITE in Chicago and the second interview is ON-SITE not negotiable.\n\nJoin our clients team as a .NET Core Developer focused on building scalable, microservices-based applications. You’ll work with modern technologies like Kafka, Docker, and Kubernetes to deliver high-performance systems.\n\nKey Responsibilities:\n• Develop microservices using .NET Core, C#, and Entity Framework Core\n• Integrate messaging systems with Kafka\n• Containerize apps with Docker and deploy via Kubernetes\n• Design and optimize SQL Server databases\n• Collaborate with DevOps, QA, and other teams\n• Troubleshoot issues and maintain documentation\n\nWhat We’re Looking For:\n• 5+ years of .NET Core development experience\n• Strong in Kafka, Docker, Kubernetes, and SQL Server\n• Familiar with cloud platforms (Azure/AWS) and CI/CD pipelines\n• Excellent problem-solving and communication skills\n\nPreferred:\n• Experience in Agile/Scrum teams\n• Background in finance or investment banking\n• Certifications in .NET or Kubernetes\n\nThank you\n\nvinayaitengagements.com",
    job_is_remote: false,
    job_posted_at: "23 hours ago",
    job_posted_at_timestamp: 1751374800,
    job_posted_at_datetime_utc: "2025-07-01T13:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DzpsZQLZ5duQi3MKKAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_min_salary: 80,
    job_max_salary: 85,
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "5+ years of .NET Core development experience",
        "Strong in Kafka, Docker, Kubernetes, and SQL Server",
        "Familiar with cloud platforms (Azure/AWS) and CI/CD pipelines",
        "Excellent problem-solving and communication skills",
      ],
      Responsibilities: [
        "Join our clients team as a .NET Core Developer focused on building scalable, microservices-based applications",
        "You’ll work with modern technologies like Kafka, Docker, and Kubernetes to deliver high-performance systems",
        "Develop microservices using .NET Core, C#, and Entity Framework Core",
        "Integrate messaging systems with Kafka",
        "Containerize apps with Docker and deploy via Kubernetes",
        "Design and optimize SQL Server databases",
        "Collaborate with DevOps, QA, and other teams",
        "Troubleshoot issues and maintain documentation",
      ],
    },
    job_onet_soc: "43411100",
    job_onet_job_zone: "2",
  },

  {
    job_id: "I0KpJ4VSKR8VP7NGAAAAAA==",
    job_title:
      "Senior Tableau Developer - Chicago, IL (W2 and Hybrid) F2F Interview",
    employer_name: "Jobs via Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9CC1NlnLA7sshF1s1dqKvk8U495jsMwImnyPP&s=0",
    employer_website: null,
    job_publisher: "LinkedIn",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.linkedin.com/jobs/view/senior-tableau-developer-chicago-il-w2-and-hybrid-f2f-interview-at-jobs-via-dice-4258748850?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/senior-tableau-developer-chicago-il-w2-and-hybrid-f2f-interview-at-jobs-via-dice-4258748850?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/e26fd89a-c3b5-4516-a3e3-39d47ea003a8?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: true,
      },
    ],
    job_description:
      "Dice is the leading career destination for tech experts at every stage of their careers. Our client, Collaborate Solutions, Inc., is seeking the following. Apply via Dice today!\n\nSenior Tableau Developer\n\nLocation :: Chicago, IL - Hybrid\n\nDuration :: 6+ Months W2 Contract\n\nIV Highlights\n• Dashboard Design the person has to do it right in front of the manager in the interview\n• Write Complex SQL query in the IV.\n\nJob Summary: Highly experienced Senior Tableau Developer with 12+ years of experience in designing, implementing, and maintaining large-scale Tableau installations with SQL Server databases, and expertise in performance improvement and optimization.\n\nCertification in Tableau or related technologies\n\nKey Responsibilities:\n• Design and implement large-scale Tableau installations\n• Develop and enforce best practices for Tableau administration and performance tuning\n• Identify and troubleshoot performance issues in Tableau dashboards and data models\n• Optimize and improve performance of Tableau workbooks, dashboards, and data sources\n• Develop and implement data storytelling and visualization best practices\n• Design and implement complex data models, including star and snowflake schemas\n• Develop and optimize Tableau calculations, including level of detail, data blending, and data densification\n\nRequirements:\n• 8+ years of experience in Tableau administration, development, and architecture\n• 5+ years of experience with SQL Server, data warehousing, and dimensional modeling concepts\n• Strong understanding of Tableau's underlying architecture and security structures\n• Expertise in developing complex Tableau dashboards, data visualizations, and data models\n• Strong SQL skills, with experience writing efficient and optimized SQL queries\n• Experience with performance optimization and troubleshooting in Tableau\n\nTechnical Skills:\n• Tableau Server, Tableau Desktop, and Tableau Online\n• SQL Server and PostgreSQL\n• Data warehousing and dimensional modeling concepts\n• Tableau Data Model and data governance tools, such as Tableau Metadata API\n• Data visualization best practices and data storytelling principles\n• Tableau calculations, including:\n• Level of detail (LOD) expressions\n• Data blending and data fusion\n• Data densification and aggregation\n• Parameter-based calculations and filters\n• Performance optimization and troubleshooting, including:\n• Identifying and resolving performance bottlenecks\n• Optimizing workbook and dashboard performance\n• Improving data source and query performance\n• Using Tableau's built-in performance monitoring and analysis tools\n• Experience with advanced Tableau features, such as:\n• Tableau Prep and data preparation best practices\n• Tableau Catalog and data governance\n• Tableau Server administration and configuration, including:\n• User and group management\n• Content and data management\n• Performance and scalability optimization\n• Tableau API and integration with other tools and systems, including:\n• REST API and webhooks\n• Tableau Connector and data source integration\n• Tableau and Python integration using TabPy\n\nPerformance Optimization Skills:\n• Experience with Tableau's performance monitoring and analysis tools, including:\n• Workbook and dashboard performance analysis\n• Data source and query performance analysis\n• Server and database performance analysis\n• Knowledge of performance optimization techniques, including:\n• Data aggregation and summarization\n• Data caching and indexing\n• Query optimization and rewriting\n• Workbook and dashboard optimization\n• Experience with optimizing Tableau for large datasets, including:\n• Data sampling and aggregation\n• Data visualization and rendering optimization\n• Workbook and dashboard optimization for large datasets",
    job_is_remote: false,
    job_posted_at: "18 hours ago",
    job_posted_at_timestamp: 1751392800,
    job_posted_at_datetime_utc: "2025-07-01T18:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DI0KpJ4VSKR8VP7NGAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Job Summary: Highly experienced Senior Tableau Developer with 12+ years of experience in designing, implementing, and maintaining large-scale Tableau installations with SQL Server databases, and expertise in performance improvement and optimization",
        "Certification in Tableau or related technologies",
        "8+ years of experience in Tableau administration, development, and architecture",
        "5+ years of experience with SQL Server, data warehousing, and dimensional modeling concepts",
        "Strong understanding of Tableau's underlying architecture and security structures",
        "Expertise in developing complex Tableau dashboards, data visualizations, and data models",
        "Strong SQL skills, with experience writing efficient and optimized SQL queries",
        "Experience with performance optimization and troubleshooting in Tableau",
        "Tableau Server, Tableau Desktop, and Tableau Online",
        "SQL Server and PostgreSQL",
        "Data warehousing and dimensional modeling concepts",
        "Tableau Data Model and data governance tools, such as Tableau Metadata API",
        "Data visualization best practices and data storytelling principles",
        "Level of detail (LOD) expressions",
        "Data blending and data fusion",
        "Using Tableau's built-in performance monitoring and analysis tools",
        "Experience with advanced Tableau features, such as:",
        "Tableau Prep and data preparation best practices",
        "Tableau Server administration and configuration, including:",
        "Content and data management",
        "Tableau API and integration with other tools and systems, including:",
        "Tableau and Python integration using TabPy",
        "Experience with Tableau's performance monitoring and analysis tools, including:",
        "Workbook and dashboard performance analysis",
        "Data source and query performance analysis",
        "Server and database performance analysis",
        "Knowledge of performance optimization techniques, including:",
        "Data aggregation and summarization",
        "Data caching and indexing",
        "Query optimization and rewriting",
        "Workbook and dashboard optimization",
        "Experience with optimizing Tableau for large datasets, including:",
        "Data sampling and aggregation",
        "Data visualization and rendering optimization",
        "Workbook and dashboard optimization for large datasets",
      ],
      Responsibilities: [
        "Dashboard Design the person has to do it right in front of the manager in the interview",
        "Write Complex SQL query in the IV",
        "Design and implement large-scale Tableau installations",
        "Develop and enforce best practices for Tableau administration and performance tuning",
        "Identify and troubleshoot performance issues in Tableau dashboards and data models",
        "Optimize and improve performance of Tableau workbooks, dashboards, and data sources",
        "Develop and implement data storytelling and visualization best practices",
        "Design and implement complex data models, including star and snowflake schemas",
        "Develop and optimize Tableau calculations, including level of detail, data blending, and data densification",
        "Tableau calculations, including:",
        "Data densification and aggregation",
        "Parameter-based calculations and filters",
        "Performance optimization and troubleshooting, including:",
        "Identifying and resolving performance bottlenecks",
        "Optimizing workbook and dashboard performance",
        "Improving data source and query performance",
        "Tableau Catalog and data governance",
        "User and group management",
        "Performance and scalability optimization",
        "REST API and webhooks",
        "Tableau Connector and data source integration",
      ],
    },
    job_onet_soc: "13208100",
    job_onet_job_zone: "3",
  },

  {
    job_id: "FzS7yhFLldOoG44LAAAAAA==",
    job_title: "Developer - .Net, C# Information Technology",
    employer_name: "United Airlines",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6e93QF6Pdyb8sYG-83_wUFBI3uqDijJVqqAKm&s=0",
    employer_website: "https://www.united.com",
    job_publisher: "United Airlines Jobs",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://careers.united.com/us/en/job/WHQ00024903/Developer-Net-C-Information-Technology?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "United Airlines Jobs",
        apply_link:
          "https://careers.united.com/us/en/job/WHQ00024903/Developer-Net-C-Information-Technology?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Indeed",
        apply_link:
          "https://www.indeed.com/viewjob?jk=4cb705f9888543b8&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/United-Airlines,-Inc./Job/Developer-.Net,-C-Information-Technology/-in-Chicago,IL?jid=c5006666c762bd70&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Dice",
        apply_link:
          "https://www.dice.com/job-detail/51fd94af-7c18-4203-bab5-5afe48509b7f?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Glassdoor",
        apply_link:
          "https://www.glassdoor.com/job-listing/developer-net-c-information-technology-united-airlines-JV_IC1128808_KO0,38_KE39,54.htm?jl=1009665146861&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/developer-net-c%23-information-technology-at-united-airlines-4179146970?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "SimplyHired",
        apply_link:
          "https://www.simplyhired.com/job/-LWia5_BMsDZKeP6czR7902xgaW_zloY8ox1uP_qgJXZOqXbEgeLGg?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Ladders",
        apply_link:
          "https://www.theladders.com/job/c-developer-core-technology-maven-chicago-il_81426051?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "Achieving our goals starts with supporting yours. Grow your career, access top-tier health and wellness benefits, build lasting connections with your team and our customers, and travel the world using our extensive route network.\n\nCome join us to create what’s next. Let’s define tomorrow, together.\n\nDescription\n\nFind your future at United! We’re reinventing what our industry looks like, and what an airline can be – from the planes we fly to the people who fly them. When you join us, you’re joining a global team of 100,000+ connected by a shared passion with a wide spectrum of experience and skills to lead the way forward.\n\nAchieving our ambitions starts with supporting yours. Evolve your career and find your next opportunity. Get the care you need with industry-leading health plans and best-in-class programs to support your emotional, physical, and financial wellness. Expand your horizons with travel across the world’s biggest route network. Connect outside your team through employee-led Business Resource Groups.\n\nCreate what’s next with us. Let’s define tomorrow together.\n\nUnited's Digital Technology team is comprised of many talented individuals all working together with cutting-edge technology to build the best airline in the history of aviation. Our team designs, develops and maintains massively scaling technology solutions brought to life with innovative architectures, data analytics, and digital solutions.\n\nJob overview and responsibilities\n\nThe Developer plays an important role in creating and maintaining the strategic partnership between business needs and technology delivery. The Developer's role is to plan, design, develop and launch efficient systems and solutions in support of core organizational functions. This individual will utilize effective communication, analytical, and problem-solving skills to help identify, communicate / resolve issues, opportunities, or problems to maximize the benefit of IT and Business investments. The Developer is experienced and self - sufficient in performing their responsibilities requiring little supervision, but general guidance and direction.\n• Assist in design, develop and modify software applications/systems\n• Collaborates with cross-functional teams to understand business requirements and deliver solutions\n• Provides support to the software development leads (Ex: Senior Developer)\n• Works on one or more moderate to complex projects\n• Applies security code best practices throughout development cycle\n• Contributes to software documentation and user manuals\n• Complete comprehensive unit testing on all developed/enhanced software and supports deployment of software applications\n• Participates in code reviews to ensure code adheres to standards\n• Support and troubleshoot software systems as required, optimizing performance, resolving problems, and providing follow-up on all issues and solutions\n• Stays up to date on the latest industry trends and technology\n\nQualifications\n\nWhat’s needed to succeed (Minimum Qualifications):\n• Bachelor's degree in Computer Science, Computer Engineering, Electrical Engineering, Management Information Systems or related field\n• 3-5 years of experience in design, development, documenting, testing, and debugging of new and existing software systems and/or applications for market sale or large-scale proprietary software for internal use in an agile environment\n• Strong knowledge of Microsoft .NET Framework, Microsoft .NET Core, SQL, T-SQL, NoSQL and Design Patterns\n• Experience implementing AWS technologies (Lambda, Step Functions, CloudWatch, CloudFront, Cognito, route53, Dynamo DB, ECS, EC2, S3, RDS, API Gateway)\n• Previous history working in an enterprise environment with experience in DevOps and CI/CD principles\n• Experience with Cloud Automation Development Tool such as Git, Python/Bash/PowerShell Scripting\n• Hands-on development and proficient excellence in backend API development\n• Excellent knowledge of Object-Oriented systems design and Application Development\n• Must be legally authorized to work in the United States for any employer without sponsorship\n• Successful completion of interview required to meet job qualification\n• Reliable, punctual attendance is an essential function of the position\n\nWhat will help you propel from the pack (Preferred Qualifications):\n• Airlines industry experience is a plus\n• AWS highly preferred\n• Experience with modern day Javascript, React.js is highly preferred\n\nThe base pay range for this role is $87,780.00 to $119,680.00.\nThe base salary range/hourly rate listed is dependent on job-related, factors such as experience, education, and skills. This position is also eligible for bonus and/or long-term incentive compensation awards.\n\nYou may be eligible for the following competitive benefits: medical, dental, vision, life, accident & disability, parental leave, employee assistance program, commuter, paid holidays, paid time off, 401(k) and flight privileges.\n\nUnited Airlines is an equal opportunity employer. United Airlines recruits, employs, trains, compensates and promotes regardless of race, religion, color, national origin, gender identity, sexual orientation, physical ability, age, veteran status and other protected status as required by applicable law. Equal Opportunity Employer - Minorities/Women/Veterans/Disabled/LGBT.\n\nWe will ensure that individuals with disabilities are provided reasonable accommodation to participate in the job application or interview process, to perform crucial job functions. Please contact JobAccommodations@united.com to request accommodation.",
    job_is_remote: false,
    job_posted_at: "2 days ago",
    job_posted_at_timestamp: 1751241600,
    job_posted_at_datetime_utc: "2025-06-30T00:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: ["dental_coverage", "paid_time_off", "health_insurance"],
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DFzS7yhFLldOoG44LAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science, Computer Engineering, Electrical Engineering, Management Information Systems or related field",
        "3-5 years of experience in design, development, documenting, testing, and debugging of new and existing software systems and/or applications for market sale or large-scale proprietary software for internal use in an agile environment",
        "Strong knowledge of Microsoft .NET Framework, Microsoft .NET Core, SQL, T-SQL, NoSQL and Design Patterns",
        "Experience implementing AWS technologies (Lambda, Step Functions, CloudWatch, CloudFront, Cognito, route53, Dynamo DB, ECS, EC2, S3, RDS, API Gateway)",
        "Previous history working in an enterprise environment with experience in DevOps and CI/CD principles",
        "Experience with Cloud Automation Development Tool such as Git, Python/Bash/PowerShell Scripting",
        "Hands-on development and proficient excellence in backend API development",
        "Excellent knowledge of Object-Oriented systems design and Application Development",
        "Must be legally authorized to work in the United States for any employer without sponsorship",
        "Successful completion of interview required to meet job qualification",
        "Reliable, punctual attendance is an essential function of the position",
      ],
      Benefits: [
        "Get the care you need with industry-leading health plans and best-in-class programs to support your emotional, physical, and financial wellness",
        "The base pay range for this role is $87,780.00 to $119,680.00",
        "The base salary range/hourly rate listed is dependent on job-related, factors such as experience, education, and skills",
        "This position is also eligible for bonus and/or long-term incentive compensation awards",
        "You may be eligible for the following competitive benefits: medical, dental, vision, life, accident & disability, parental leave, employee assistance program, commuter, paid holidays, paid time off, 401(k) and flight privileges",
      ],
      Responsibilities: [
        "Expand your horizons with travel across the world’s biggest route network",
        "The Developer plays an important role in creating and maintaining the strategic partnership between business needs and technology delivery",
        "The Developer's role is to plan, design, develop and launch efficient systems and solutions in support of core organizational functions",
        "This individual will utilize effective communication, analytical, and problem-solving skills to help identify, communicate / resolve issues, opportunities, or problems to maximize the benefit of IT and Business investments",
        "The Developer is experienced and self - sufficient in performing their responsibilities requiring little supervision, but general guidance and direction",
        "Assist in design, develop and modify software applications/systems",
        "Collaborates with cross-functional teams to understand business requirements and deliver solutions",
        "Provides support to the software development leads (Ex: Senior Developer)",
        "Works on one or more moderate to complex projects",
        "Applies security code best practices throughout development cycle",
        "Contributes to software documentation and user manuals",
        "Complete comprehensive unit testing on all developed/enhanced software and supports deployment of software applications",
        "Participates in code reviews to ensure code adheres to standards",
        "Support and troubleshoot software systems as required, optimizing performance, resolving problems, and providing follow-up on all issues and solutions",
        "Stays up to date on the latest industry trends and technology",
      ],
    },
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },

  {
    job_id: "wLofJ9d6w36VxXmfAAAAAA==",
    job_title: "Hybrid Sr. Software Engineer (No C2C)",
    employer_name: "Solving IT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRog7WIInxpvfqgve-XrtEBHjwoK59L65WoJ1rW&s=0",
    employer_website: "https://solvingit.com",
    job_publisher: "LinkedIn",
    job_employment_type: "Contractor",
    job_employment_types: ["CONTRACTOR", "CONTRACTOR"],
    job_apply_link:
      "https://www.linkedin.com/jobs/view/hybrid-sr-software-engineer-no-c2c-at-solving-it-4258731030?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/hybrid-sr-software-engineer-no-c2c-at-solving-it-4258731030?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
      {
        publisher: "Ladders",
        apply_link:
          "https://www.theladders.com/job/sr-new-relic-developer-no-c2c-xlysi-chicago-il_76951121?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "No C2C: Hybrid Senior Software Engineer (Financial Services)-Chicago\n\nHybrid-3 days a week in Chicago\n\nInterview: Onsite Interview and Live Glider AI assessment\n\nRate: $55-$60 (based on experience)\n\nContract: 6 Months; goal is to extend\n• Our client is unable to sponsor\n\nOur Financial Services client is seeking a Contract Senior Software Engineer that is responsible for developing secure, scalable, and reliable technology solutions with minimal supervision. This role requires strong technical expertise, a problem-solving mindset, and the ability to work collaboratively across teams.\n\nKey Responsibilities:\n• Design, develop, troubleshoot, and debug web applications using modern technologies.\n• Write application modules and unit tests with minimal guidance.\n• Conduct system-wide and integration testing to ensure software quality and performance.\n• Review code to proactively identify and resolve issues, mitigate defects, and troubleshoot various types of errors.\n• Collaborate with stakeholders to define, refine, and finalize business and technical requirements.\n• Participate in code reviews and contribute to build deployments, release documentation, and environment notifications.\n• Communicate and share design ideas using appropriate design tools and documentation.\n• Apply and advocate for best practices, design patterns, and process improvements.\n• Adhere to software development life cycle (SDLC) and information security standards.\n\nRequired Qualifications:\n• Bachelor’s degree in Computer Science or related field preferred; equivalent experience will be considered.\n• Strong hands-on experience with Java, Spring Boot, and Spring Batch.\n• Proficiency in SQL and database development.\n• Solid understanding of server-side design patterns.\n• Familiarity with version control and build tools such as Git, Maven, and CI/CD pipelines.\n• Strong troubleshooting and problem-solving skills.\n• Excellent communication and collaboration abilities.\n\nPreferred Qualifications:\n• Experience with Google Cloud Platform (GCP) services.\n• Proficiency with Unix/Linux systems.\n• Experience in developing and automating CI/CD solutions and infrastructure automation.\n• Ability to lead and clarify code enhancements during code reviews.",
    job_is_remote: false,
    job_posted_at: "21 hours ago",
    job_posted_at_timestamp: 1751382000,
    job_posted_at_datetime_utc: "2025-07-01T15:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DwLofJ9d6w36VxXmfAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_min_salary: 55,
    job_max_salary: 60,
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "This role requires strong technical expertise, a problem-solving mindset, and the ability to work collaboratively across teams",
        "Strong hands-on experience with Java, Spring Boot, and Spring Batch",
        "Proficiency in SQL and database development",
        "Solid understanding of server-side design patterns",
        "Familiarity with version control and build tools such as Git, Maven, and CI/CD pipelines",
        "Strong troubleshooting and problem-solving skills",
        "Excellent communication and collaboration abilities",
      ],
      Benefits: [
        "Rate: $55-$60 (based on experience)",
        "Our client is unable to sponsor",
      ],
      Responsibilities: [
        "Design, develop, troubleshoot, and debug web applications using modern technologies",
        "Write application modules and unit tests with minimal guidance",
        "Conduct system-wide and integration testing to ensure software quality and performance",
        "Review code to proactively identify and resolve issues, mitigate defects, and troubleshoot various types of errors",
        "Collaborate with stakeholders to define, refine, and finalize business and technical requirements",
        "Participate in code reviews and contribute to build deployments, release documentation, and environment notifications",
        "Communicate and share design ideas using appropriate design tools and documentation",
        "Apply and advocate for best practices, design patterns, and process improvements",
        "Adhere to software development life cycle (SDLC) and information security standards",
      ],
    },
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },

  {
    job_id: "X8vff7esFaC7hk4hAAAAAA==",
    job_title: "Web Developer",
    employer_name: "Adaptive Health",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwnCd7DoiijZdoEoOJE0kH3ypd1Jefr86fTm60&s=0",
    employer_website: "http://adaptivehealth.com/",
    job_publisher: "Indeed",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.indeed.com/viewjob?jk=97ad8e5a6a7e1132&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "Indeed",
        apply_link:
          "https://www.indeed.com/viewjob?jk=97ad8e5a6a7e1132&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "Overview\n\nAdaptive Health is looking for an experienced web developer to help design, build, and maintain the next generation of applications for mental health. Duties will include collaboration with the clinical and business teams, understanding and developing new features, identifying and fixing application bottlenecks, and maintaining the application.\n\nYou must have a working knowledge of web development, and be able to work as part of a team.\n\nThe developer will report directly to the CTO.\n\nWeb Developer Responsibilities:\n\nDesigning and building web applications\n\nDefining and implementing new features\n\nEnsuring quality and performance of the application\n\nIdentifying potential problems and resolving application bottlenecks\n\nFixing application bugs\n\nDesigning and implementing application updates\n\nWeb Developer Requirements:\n\nBachelor’s degree in computer science, software engineering, or equivalent\n\nPrior experience as an app developer\n\nProficiency in HTML5, CSS2, JavaScript, and an understanding of a broad range of web technologies\n\nKnowledge of we design principles and application interface guidelines\n\nExperience with version control using Git\n\nUnderstanding of and experience with REST APIs\n\nFamiliarity with information security and privacy concerns, preferably with respect to HIPAA requirements\n\nExperience with SDLC projects from requirements through support\n\nExcellent debugging and problem solving skills\n\nStrong verbal and written communications skills\n\nMust be self directed, analytical, and work well in a team environment",
    job_is_remote: false,
    job_posted_at: null,
    job_posted_at_timestamp: null,
    job_posted_at_datetime_utc: null,
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DX8vff7esFaC7hk4hAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "You must have a working knowledge of web development, and be able to work as part of a team",
        "Designing and building web applications",
        "Bachelor’s degree in computer science, software engineering, or equivalent",
        "Prior experience as an app developer",
        "Proficiency in HTML5, CSS2, JavaScript, and an understanding of a broad range of web technologies",
        "Knowledge of we design principles and application interface guidelines",
        "Experience with version control using Git",
        "Understanding of and experience with REST APIs",
        "Familiarity with information security and privacy concerns, preferably with respect to HIPAA requirements",
        "Experience with SDLC projects from requirements through support",
        "Excellent debugging and problem solving skills",
        "Strong verbal and written communications skills",
        "Must be self directed, analytical, and work well in a team environment",
      ],
      Responsibilities: [
        "Adaptive Health is looking for an experienced web developer to help design, build, and maintain the next generation of applications for mental health",
        "Duties will include collaboration with the clinical and business teams, understanding and developing new features, identifying and fixing application bottlenecks, and maintaining the application",
        "The developer will report directly to the CTO",
        "Defining and implementing new features",
        "Ensuring quality and performance of the application",
        "Identifying potential problems and resolving application bottlenecks",
        "Fixing application bugs",
        "Designing and implementing application updates",
      ],
    },
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },

  {
    job_id: "DQkf1JIXq6HenW6IAAAAAA==",
    job_title: "Full Stack AI Engineer - Advanced AI Agents",
    employer_name: "FoodReady",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgZ7JeoYo9tZzO422H5b48KbDvp-moFgTNJu6I&s=0",
    employer_website: "http://foodready.ai/",
    job_publisher: "LinkedIn",
    job_employment_type: "Full-time",
    job_employment_types: ["FULLTIME"],
    job_apply_link:
      "https://www.linkedin.com/jobs/view/full-stack-ai-engineer-advanced-ai-agents-at-foodready-4260522057?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_apply_is_direct: false,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/full-stack-ai-engineer-advanced-ai-agents-at-foodready-4260522057?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
        is_direct: false,
      },
    ],
    job_description:
      "About This Role\n\nWe're seeking an exceptional Full Stack Engineer who thrives at the intersection of cutting-edge AI and scalable software engineering. You'll architect and build the world's most sophisticated AI agents while owning the entire technical stack from database to user interface. This isn't just about implementing existing solutions—you'll pioneer new approaches to AI agent architecture and push the boundaries of what's possible.\n\nWhat You'll Build\n\nRevolutionary AI Agent Systems\n• Design and implement autonomous AI agents capable of complex planning, and execution\n• Build sophisticated agent orchestration systems that coordinate multiple AI models and tools\n• Develop novel approaches to agent memory, learning, and adaptation\n• Create intelligent routing and decision-making systems for multi-agent environments\n\nFull Stack Excellence\n• Architect robust backend systems that can handle real-time AI inference at scale\n• Build intuitive, responsive frontends that make complex AI capabilities accessible\n• Design and optimize databases for high-performance AI workloads and vector storage\n• Implement real-time communication systems for agent-human and agent-agent interaction\n\nInnovation & Research\n• Experiment with the latest AI models, frameworks, and techniques (GPT-4+, Claude, custom models)\n• Prototype and validate new AI agent capabilities and interaction patterns\n• Contribute to open-source AI tools and publish technical insights\n• Stay ahead of the rapidly evolving AI landscape and integrate breakthrough technologies\n\nWhat We're Looking For\n\nTechnical Mastery\n• 5+ years of full stack development with modern frameworks (React/Next.js, Node.js, Python, Go, or similar)\n• Deep understanding of AI/ML fundamentals: transformers, embeddings, vector databases, fine-tuning\n• Experience with LLM APIs, prompt engineering, and AI model integration\n• Proficiency with cloud platforms (AWS, GCP, Azure) and containerization (Docker, Kubernetes)\n• Strong database design skills (i.e. PostgreSQL, MongoDB, vector databases, etc.)\n\nAI Agent Expertise\n• Experience building AI agents, chatbots, or autonomous systems\n• Understanding of agent frameworks (LangChain, CrewAI, AutoGPT, or custom implementations)\n• Knowledge of reinforcement learning, multi-agent systems, or planning algorithms\n• Familiarity with tool use, function calling, and external API integration for AI systems\n\nEntrepreneurial Mindset\n• Owner mentality: You take full ownership of problems and drive them to completion\n• Business acumen: You understand how technical decisions impact user experience and business outcomes\n• Resourcefulness: You find creative solutions with limited resources and tight timelines\n• Vision: You can see the bigger picture and build systems that scale with the company's growth\n\nProblem-Solving Excellence\n• Systems thinking: You design elegant solutions that consider the entire system\n• Debugging mastery: You can troubleshoot complex issues across the entire stack\n• Performance optimization: You build systems that are fast, reliable, and cost-effective\n• User-centric approach: You prioritize solutions that deliver real value to end users\n\nIntellectual Curiosity\n• Continuous learning: You actively stay current with the latest AI research and engineering practices\n• Experimentation: You love prototyping new ideas and aren't afraid to fail fast and iterate\n• Cross-functional collaboration: You enjoy working with researchers, designers, and product teams\n• Teaching and sharing: You contribute to team knowledge and help others grow\n\nTechnical Environment\n\nAI & Machine Learning\n• Latest LLMs (GPT-4, Claude Sonnet, Gemini, open-source models)\n• Vector databases and semantic search systems\n• Real-time inference optimization and caching strategies\n• Custom model fine-tuning and deployment pipelines\n\nBackend Technologies\n• Microservices architecture with event-driven design\n• Real-time APIs (WebSockets, Server-Sent Events)\n• Message queues and distributed task processing\n• High-performance data pipelines and ETL systems\n\nFrontend Excellence\n• Modern React/TypeScript applications with sophisticated state management\n• Real-time user interfaces for AI agent monitoring and control\n• Interactive data visualization and analytics dashboards\n• Mobile-responsive design with accessibility focus\n\nInfrastructure & DevOps\n• Container orchestration and auto-scaling systems\n• CI/CD pipelines with automated testing and deployment\n• Monitoring, logging, and observability for AI systems\n• Cost optimization for GPU compute and inference workloads\n\nWhat Success Looks Like\n\n6 Months: You've shipped multiple AI agent features that users love, optimized our inference pipeline for 10x better performance, and become the go-to person for complex technical challenges.\n\n1 Year: You've architected and built a groundbreaking AI agent system that sets new industry standards, mentored junior engineers, and contributed significantly to our technical strategy and product roadmap.\n\n2 Years: You're recognized as a thought leader in AI agent engineering, have launched features that transformed how users interact with AI, and are helping shape the future direction of autonomous AI systems.\n\nWhy You'll Thrive Here\n• Cutting-edge technology: Work with the latest AI models and techniques before they become mainstream\n• Massive impact: Your code will be used by millions of users and push the boundaries of AI capabilities\n• Learning environment: Collaborate with world-class AI researchers and engineers\n• Ownership culture: Take full ownership of features from conception to deployment\n• Innovation freedom: 20% time for personal projects and research that interests you\n\nReady to Build the Future?\n\nIf you're excited about building AI systems that seemed impossible just a few years ago, thrive in fast-paced environments, and want to be at the forefront of the AI revolution, we want to hear from you.\n\nSend us your resume along with:\n• Examples of AI projects you've built (GitHub repos, demos, or case studies)\n• A brief note about the most interesting technical problem you've solved recently\n• Your thoughts on where AI agent technology is heading in the next 2-3 years",
    job_is_remote: false,
    job_posted_at: "10 hours ago",
    job_posted_at_timestamp: 1751421600,
    job_posted_at_datetime_utc: "2025-07-02T02:00:00.000Z",
    job_location: "Chicago, IL",
    job_city: "Chicago",
    job_state: "Illinois",
    job_country: "US",
    job_latitude: 41.88325,
    job_longitude: -87.6323879,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?q=jobs&gl=us&hl=en&udm=8#vhid=vt%3D20/docid%3DDQkf1JIXq6HenW6IAAAAAA%3D%3D&vssid=jobs-detail-viewer",
    job_salary: null,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Architect robust backend systems that can handle real-time AI inference at scale",
        "Technical Mastery",
        "5+ years of full stack development with modern frameworks (React/Next.js, Node.js, Python, Go, or similar)",
        "Deep understanding of AI/ML fundamentals: transformers, embeddings, vector databases, fine-tuning",
        "Experience with LLM APIs, prompt engineering, and AI model integration",
        "Proficiency with cloud platforms (AWS, GCP, Azure) and containerization (Docker, Kubernetes)",
        "Strong database design skills (i.e",
        "PostgreSQL, MongoDB, vector databases, etc.)",
        "Experience building AI agents, chatbots, or autonomous systems",
        "Understanding of agent frameworks (LangChain, CrewAI, AutoGPT, or custom implementations)",
        "Knowledge of reinforcement learning, multi-agent systems, or planning algorithms",
        "Familiarity with tool use, function calling, and external API integration for AI systems",
        "Entrepreneurial Mindset",
        "Owner mentality: You take full ownership of problems and drive them to completion",
        "Business acumen: You understand how technical decisions impact user experience and business outcomes",
        "Resourcefulness: You find creative solutions with limited resources and tight timelines",
        "Vision: You can see the bigger picture and build systems that scale with the company's growth",
        "Problem-Solving Excellence",
        "Systems thinking: You design elegant solutions that consider the entire system",
        "User-centric approach: You prioritize solutions that deliver real value to end users",
        "Intellectual Curiosity",
        "Continuous learning: You actively stay current with the latest AI research and engineering practices",
        "Experimentation: You love prototyping new ideas and aren't afraid to fail fast and iterate",
        "Cross-functional collaboration: You enjoy working with researchers, designers, and product teams",
        "Teaching and sharing: You contribute to team knowledge and help others grow",
        "Vector databases and semantic search systems",
        "High-performance data pipelines and ETL systems",
        "Frontend Excellence",
        "Modern React/TypeScript applications with sophisticated state management",
        "Real-time user interfaces for AI agent monitoring and control",
        "Interactive data visualization and analytics dashboards",
        "Mobile-responsive design with accessibility focus",
        "Container orchestration and auto-scaling systems",
        "6 Months: You've shipped multiple AI agent features that users love, optimized our inference pipeline for 10x better performance, and become the go-to person for complex technical challenges",
      ],
      Benefits: [
        "Cutting-edge technology: Work with the latest AI models and techniques before they become mainstream",
        "Learning environment: Collaborate with world-class AI researchers and engineers",
        "Ownership culture: Take full ownership of features from conception to deployment",
        "Innovation freedom: 20% time for personal projects and research that interests you",
      ],
      Responsibilities: [
        "You'll architect and build the world's most sophisticated AI agents while owning the entire technical stack from database to user interface",
        "Design and implement autonomous AI agents capable of complex planning, and execution",
        "Build sophisticated agent orchestration systems that coordinate multiple AI models and tools",
        "Develop novel approaches to agent memory, learning, and adaptation",
        "Create intelligent routing and decision-making systems for multi-agent environments",
        "Full Stack Excellence",
        "Build intuitive, responsive frontends that make complex AI capabilities accessible",
        "Design and optimize databases for high-performance AI workloads and vector storage",
        "Implement real-time communication systems for agent-human and agent-agent interaction",
        "Experiment with the latest AI models, frameworks, and techniques (GPT-4+, Claude, custom models)",
        "Prototype and validate new AI agent capabilities and interaction patterns",
        "Contribute to open-source AI tools and publish technical insights",
        "Stay ahead of the rapidly evolving AI landscape and integrate breakthrough technologies",
        "Debugging mastery: You can troubleshoot complex issues across the entire stack",
        "Performance optimization: You build systems that are fast, reliable, and cost-effective",
        "Real-time inference optimization and caching strategies",
        "Custom model fine-tuning and deployment pipelines",
        "Microservices architecture with event-driven design",
        "Real-time APIs (WebSockets, Server-Sent Events)",
        "Message queues and distributed task processing",
        "CI/CD pipelines with automated testing and deployment",
        "Monitoring, logging, and observability for AI systems",
        "Cost optimization for GPU compute and inference workloads",
      ],
    },
    job_onet_soc: "15111100",
    job_onet_job_zone: "5",
  },
];
